/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortCodeRouteImport } from './routes/$shortCode'
import { Route as IndexRouteImport } from './routes/index'

const ShortCodeRoute = ShortCodeRouteImport.update({
  id: '/$shortCode',
  path: '/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shortCode': typeof ShortCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shortCode': typeof ShortCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shortCode': typeof ShortCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$shortCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$shortCode'
  id: '__root__' | '/' | '/$shortCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortCodeRoute: typeof ShortCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$shortCode': {
      id: '/$shortCode'
      path: '/$shortCode'
      fullPath: '/$shortCode'
      preLoaderRoute: typeof ShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortCodeRoute: ShortCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
